name: bash-language-server
version: '4.7.0'
summary: Bash Language Server
description: |
  Features:
  * Jump to declaration
  * Find references
  * Code Outline & Show Symbols
  * Highlight occurrences
  * Code completion
  * Simple diagnostics reporting
  * Documentation for flags on hover

grade: stable
confinement: classic
base: core20

apps:
  bash-language-server:
    command: bin/node $SNAP/bin/bash-language-server

parts:
  bash-language-server:
    plugin: npm
    source: https://github.com/bash-lsp/bash-language-server.git
    source-tag: server-$SNAPCRAFT_PROJECT_VERSION
    source-subdir: server
    build-environment:
      - NODEJS_FIXED_VERSION: "v16.19.1"
    npm-node-version: $NODEJS_FIXED_VERSION
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/"${NODEJS_FIXED_VERSION}"/node-"${NODEJS_FIXED_VERSION}"-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install yarn
      $SNAPCRAFT_PART_BUILD/node_modules/.bin/yarn install
      $SNAPCRAFT_PART_BUILD/node_modules/.bin/yarn run compile
      $SNAPCRAFT_PART_BUILD/node_modules/.bin/yarn run reinstall-server
      # break symlink back to build area for final install
      cp -r server $SNAPCRAFT_PART_INSTALL
      rm $SNAPCRAFT_PART_INSTALL/lib/node_modules/bash-language-server
      ln -s ../../server $SNAPCRAFT_PART_INSTALL/lib/node_modules/bash-language-server


