name: bash-language-server
version: '5.6.0'
summary: Bash Language Server
description: |
  Features:
  * Jump to declaration
  * Find references
  * Code Outline & Show Symbols
  * Highlight occurrences
  * Code completion
  * Simple diagnostics reporting
  * Documentation for flags on hover

grade: stable
confinement: classic
base: core24

apps:
  bash-language-server:
    command: bin/node $SNAP/bin/bash-language-server

parts:
  bash-language-server:
    plugin: npm
    source: https://github.com/bash-lsp/bash-language-server.git
    source-tag: server-$SNAPCRAFT_PROJECT_VERSION
    source-subdir: server
    npm-node-version: 22.13.0
    npm-include-node: true
    override-build: |
      # this will just install node and run npm install -g into
      # CRAFT_PARTS_INSTALL - we need to also actually compile the typescript
      # source into javascript
      craftctl default
      npm install -g pnpm
      # ensure devDependencies get installed by unsetting NODE_ENV as production
      unset NODE_ENV
      pnpm install
      pnpm run compile
      pnpm run reinstall-server
      cp -r node_modules $SNAPCRAFT_PART_INSTALL
      # break symlink back to build area for final install
      cp -r server $SNAPCRAFT_PART_INSTALL
      rm $SNAPCRAFT_PART_INSTALL/lib/node_modules/bash-language-server
      ln -s ../../server $SNAPCRAFT_PART_INSTALL/lib/node_modules/bash-language-server


